keycloakx:
  ingress:
    enabled: true
    rules:
      - host: testdevoxx.lab.sspcloud.fr
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - testdevoxx.lab.sspcloud.fr
