minio:
  rootUser: admin
  rootPassword: G3PJwYC467pdsuzng154bEsDom
  mode: standalone
  persistence:
    size: 1Gi
  resources:
    requests:
      memory: 512Mi
  ingress:
    enabled: true
    hosts:
      - minio.devoxx.insee.io
    tls:
      - hosts:
          - minio.devoxx.insee.io
  consoleIngress:
    enabled: true
    hosts:
      - minio-console.devoxx.insee.io
    tls:
      - hosts:
          - minio-console.devoxx.insee.io
  oidc:
    enabled: true
    configUrl: "https://auth.devoxx.insee.io/auth/realms/datalab/.well-known/openid-configuration"
    clientId: "minio"
    clientSecret: ""
    claimName: "policy"
    scopes: "openid,profile,email"
    redirectUri: "https://minio-console.devoxx.insee.io/oauth_callback"
  policies:
    - name: stsonly
      statements:
        - resources:
            - "arn:aws:s3:::oidc-${jwt:preferred_username}"
            - "arn:aws:s3:::oidc-${jwt:preferred_username}/*"
          actions:
            - "s3:*"
